const platforms=[{name:'Community Bridge',fee:0,note:'processing covered'},{name:'GitHub Sponsors',fee:0,note:'individual account'},{name:'thanks.dev',fee:3,note:'processor only'},{name:'Ko-fi',fee:3,note:'one-time tips'},{name:'Buy Me a Coffee',fee:8,note:'platform + processor'}];
const amount=document.querySelector('#amount'),results=document.querySelector('#results');
function render(){const value=Math.max(1,Number(amount?.value)||100);if(!results)return;results.innerHTML=platforms.map(item=>`<div class="result"><span class="result-name">${item.name}</span><span class="result-note">${item.note}</span><span class="result-value">$${(value*(1-item.fee/100)).toFixed(2)}</span></div>`).join('')}
amount?.addEventListener('input',render);render();
const recommendations={solo:{title:'Your recommended stack',text:'GitHub gives supporters a native path. Ko-fi covers people who prefer a familiar card or PayPal flow.'},team:{title:'Your recommended stack',text:'Use GitHub Sponsors for discovery, then add Open Collective when shared budgets and transparent ledgers matter.'},enterprise:{title:'Your recommended stack',text:'Pair a GitHub-native entry point with a written support agreement or Tidelift-style enterprise path.'}};
let mode='solo';
function refresh(){const r=recommendations[mode];document.querySelector('#builder-title').textContent=r.title;document.querySelector('#recommendation p').textContent=r.text;document.querySelector('#coverage').textContent=mode==='enterprise'?'2 rails + contract':'2 rails'}
document.querySelectorAll('.mode').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.mode').forEach(b=>b.classList.remove('active'));btn.classList.add('active');mode=btn.dataset.mode;refresh()}));
document.querySelectorAll('.stack-option').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.stack-option').forEach(b=>b.classList.remove('selected'));btn.classList.add('selected');const name=btn.querySelector('b').textContent;document.querySelector('#recommendation b').textContent=`${name} selected`;document.querySelector('#recommendation p').textContent=`${name} is now your highlighted path. Add one complementary rail to reduce payment friction.`}));
document.querySelector('#copy-config')?.addEventListener('click',async()=>{const text='github: [YOUR_USERNAME]\nko_fi: your_handle\ncustom: [https://your-payment-link]';try{await navigator.clipboard.writeText(text)}catch(e){}const el=document.querySelector('#copied');el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1600)});
document.querySelectorAll('a[href^="#"]').forEach(link=>link.addEventListener('click',event=>{const target=document.querySelector(link.getAttribute('href'));if(target){event.preventDefault();target.scrollIntoView({behavior:'smooth',block:'start'})}}));
const themeToggle=document.querySelector('#theme-toggle');
const savedTheme=localStorage.getItem('sponsor-button-theme');
const systemDark=window.matchMedia('(prefers-color-scheme: dark)').matches;
function setTheme(theme,save=true){const dark=theme==='dark';document.body.classList.toggle('theme-dark',dark);themeToggle?.setAttribute('aria-pressed',String(dark));themeToggle?.setAttribute('aria-label',dark?'Switch to light mode':'Switch to dark mode');const label=themeToggle?.querySelector('.theme-label');const thumb=themeToggle?.querySelector('.toggle-thumb');if(label)label.textContent=dark?'Dark':'Light';if(thumb)thumb.textContent=dark?'☾':'☼';if(save)localStorage.setItem('sponsor-button-theme',theme)}
setTheme(savedTheme||(systemDark?'dark':'light'),false);
themeToggle?.addEventListener('click',()=>setTheme(document.body.classList.contains('theme-dark')?'light':'dark'));
